pipeline {
    agent any
    tools {
        go '1.19'
    }
    environment {
        Go111MODULE='on'
    }

    stages {
        stage('Test') {
            steps {
                git 'https://github.com/kodekloudhub/go-webapp-sample.git'
            }
        }
        stage('Build And Run Docker Image') {
            steps {
                script {
                    image = docker.build("adminturneddevops/go-webapp-sample")
                    sh "docker run -p 8090:8000 -d adminturneddevops/go-webapp-sample"
                }
            }
        }
    }
}